### ISSUE TITLE
Implement scripts/install test etc pattern

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-plugin#11]
As seen here https://www.encode.io/reports/april-2020#our-workflow-approach

```
steps:
  - uses: "actions/checkout@v2"
  - uses: "actions/setup-python@v1"
    with:
      python-version: "$"
  - name: "Install dependencies"
    run: "scripts/install"
  - name: "Run linting checks"
    run: "scripts/check"
  - name: "Build package & docs"
    run: "scripts/build"
  - name: "Run tests"
    run: "scripts/test"
```
