### ISSUE TITLE
GitHub Action in this repo that updates simonw/datasette-plugin-template-demo

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-plugin#4]
Would be cool if this repo updated its own demo.

**Comment by simonw** [comment]
This should happen on every push to main.

**Comment by simonw** [comment]
I have this working now in that it generates the correct set of files here:

<img width="790" alt="Update_push_yml_·_simonw_datasette-plugin_ad04ee6" src="https://user-images.githubusercontent.com/9599/85177821-c666f800-b231-11ea-885e-dc992989c9c2.png">

Next step: push those files to the https://github.com/simonw/datasette-plugin-template-demo repo.

**Comment by simonw** [comment]
This is a bit tricky: I want to completely over-write the existing repo contents with the newly generated files, deleting any files that are missing and adding any new ones - all represented by a single commit.

The commit message should link back to the commit in this `datasette-plugin` repo that caused the changes.

**Comment by simonw** [comment]
I think `git add -A .` will handle the git side of things. So I need to checkout the repo, generate a clean demo with cookiecutter, then replace the checked out content with the files created by cookiecutter and run the commit.

**Comment by simonw** [comment]
I think `rsync` can do this: `rsync -av --delete /from-path /to-path`

**Comment by simonw** [comment]
Possibly easier: `mv ~/old-version/.git ~/new-version` - then run the checkin from the new version?

**Comment by simonw** [comment]
And to commit but only if it changed:
```
timestamp=$(date -u)
git commit -m "Latest data: ${timestamp}" || exit 0
```

**Comment by simonw** [comment]
I might need to do this to be able to push to the repo:
```
- name: Checkout private tools
  uses: actions/checkout@v2
  with:
    repository: my-org/my-private-tools
    token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
    path: my-tools
```
From https://github.com/actions/checkout#checkout-multiple-repos-private
